### PR TITLE
Clustering example

### PR DESCRIPTION
**Pull request by DanInci**
TODO list for example clustering:
- [x] Create benchmark YAML
- [x] Implement method modules in [custom](https://github.com/orgs/omnibenchmark-example/repositories) repositories  
- [ ] Update software backend
- [ ] Setup storage
- [ ] Update documentation on website 

Note for reviewer:
- Please review also the example module repositories for clustering, since I wrote some pretty basic analysis. They are available [here](https://github.com/orgs/omnibenchmark-example/repositories).

Topology plot:

```mermaid
---
title: clustering_benchmark
---
flowchart LR
	classDef param fill:#f96
	subgraph data
		iris
		penguins
	end
	subgraph distances
		D1
		iris --> D1
		penguins --> D1
	end
	subgraph methods
		kmeans
		D1 --> kmeans
		ward
		D1 --> ward
	end
	subgraph metrics
		ari
		kmeans --> ari
		ward --> ari
		accuracy
		kmeans --> accuracy
		ward --> accuracy
	end
	subgraph params_D1
		8948341830810125333['--measure', 'cosine']
		-6750798201292827140['--measure', 'euclidean']
		-5289070520883795694['--measure', 'manhattan']
		1540997255918402294['--measure', 'chebyshev']
	end
	params_D1:::param --o D1
```

Computational plot:
clustering

### CODE REVIEW

**Comment by retogerber** [comment]
Added the possibility to use the remote storage with play.min.io
use with (currently only works with https://github.com/omnibenchmark/omnibenchmark/tree/io_tests):
`OB_STORAGE_S3_CONFIG=.play_minio.json ob run benchmark -b Clustering.yaml`

**Comment by imallona** [comment]
@retogerber 

```
$ OB_STORAGE_S3_CONFIG=.play_minio.json ob run benchmark -b Clustering.yaml
```

raises

```
[Thu Oct 31 12:01:27 2024]
INFO:snakemake.logging:[Thu Oct 31 12:01:27 2024]
localrule data_iris_default:
    output: s3://clustering_benchmark/out/data/iris/default/iris.features.csv (send to storage), s3://clustering_benchmark/out/data/iris/default/iris.labels.csv (send to storage)
    jobid: 2
    reason: Missing output files: s3://clustering_benchmark/out/data/iris/default/iris.features.csv (send to storage), s3://clustering_benchmark/out/data/iris/default/iris.labels.csv (send to storage)
    wildcards: stage=data, module=iris, params=default, dataset=iris
    resources: tmpdir=/home/imallona/tmp/eb-ykwj4d5j/eb-tn4m4s52
INFO:snakemake.logging:localrule data_iris_default:
    output: s3://clustering_benchmark/out/data/iris/default/iris.features.csv (send to storage), s3://clustering_benchmark/out/data/iris/default/iris.labels.csv (send to storage)
    jobid: 2
    reason: Missing output files: s3://clustering_benchmark/out/data/iris/default/iris.features.csv (send to storage), s3://clustering_benchmark/out/data/iris/default/iris.labels.csv (send to storage)
    wildcards: stage=data, module=iris, params=default, dataset=iris
    resources: tmpdir=/home/imallona/tmp/eb-ykwj4d5j/eb-tn4m4s52

INFO:snakemake.logging:
/home/imallona/micromamba/envs/omnibenchmark/lib/python3.12/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'play.min.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/home/imallona/micromamba/envs/omnibenchmark/lib/python3.12/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'play.min.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
EasyBuild crashed with an error (at easybuild/tools/build_log.py:111 in caller_info): WorkflowError:
Failed to check existence of s3://clustering_benchmark/out/data/iris/default/iris.features.csv
ClientError: An error occurred (400) when calling the HeadObject operation: Bad Request
ERROR:snakemake.logging:EasyBuild crashed with an error (at easybuild/tools/build_log.py:111 in caller_info): WorkflowError:
Failed to check existence of s3://clustering_benchmark/out/data/iris/default/iris.features.csv
ClientError: An error occurred (400) when calling the HeadObject operation: Bad Request
Benchmark run has failed.
```

**Comment by imallona** [comment]
The https://github.com/omnibenchmark/omnibenchmark/pull/36 patches the run using envmodules, e.g. when `snakemake -s Snakefile  --use-envmodules` once the `Snakefile` is generated after running `ob run benchmark` (see note). Currently, the validator checks whether envmodules as files exist or not. There are (lua) files defining the envmodules somewhere, but I think is easier we check via `module avail` checks (see the drafted PR).

Note: The `ob run benchmark` does not work directly but that's an independent issue, probably due to the modulepath environmental variable not being propagated to children processes by snakemake; will open a PR.

**Comment by DanInci** [comment]
> Added the possibility to use the remote storage with play.min.io use with (currently only works with https://github.com/omnibenchmark/omnibenchmark/tree/io_tests): `OB_STORAGE_S3_CONFIG=.play_minio.json ob run benchmark -b Clustering.yaml`

Arent these sensitive tokens, or just part of a free sandbox environment? 
Would it make sense to store them as github secrets and only use remote storage examples with the CI jobs?

**Comment by retogerber** [comment]
> > Added the possibility to use the remote storage with play.min.io use with (currently only works with https://github.com/omnibenchmark/omnibenchmark/tree/io_tests): `OB_STORAGE_S3_CONFIG=.play_minio.json ob run benchmark -b Clustering.yaml`
> 
> @retogerber Arent these sensitive tokens, or just part of a free sandbox environment? Would it make sense to store them as github secrets and only use remote storage examples with the CI jobs?

@DanInci those are not sensitive but from the official minio sandbox. E.g. here: https://min.io/docs/minio/linux/developers/python/minio-py.html

**Comment by DanInci** [comment]
> > > Added the possibility to use the remote storage with play.min.io use with (currently only works with https://github.com/omnibenchmark/omnibenchmark/tree/io_tests): `OB_STORAGE_S3_CONFIG=.play_minio.json ob run benchmark -b Clustering.yaml`
> > 
> > 
> > @retogerber Arent these sensitive tokens, or just part of a free sandbox environment? Would it make sense to store them as github secrets and only use remote storage examples with the CI jobs?
> 
> @DanInci those are not sensitive but from the official minio sandbox. E.g. here: https://min.io/docs/minio/linux/developers/python/minio-py.html

Alright great, just double checking.

**Pull request merged**
